### PR TITLE
Apply additional rspec settings

### PR DESCRIPTION
**Pull request by albus522**

### CODE REVIEW

**Comment by kopchickm** [comment]
I like these changes 👍

**Comment by gaffneyc** [comment]
Not familiar with any of these settings. Is there more rationale or description on what they do?

**Comment by kopchickm** [comment]
I googled each of them:

`RSpec/DescribeClass` enforces using the class name in a `describe` block
```
# bad
describe 'Do something' do
end

# good
describe TestedClass do
end
```

`RSpec/DescribedClass` enforces using the `described_class` variable instead of the class:
```
# bad
describe MyClass do
  subject { MyClass.do_something }
end

# good
describe MyClass do
  subject { described_class.do_something }
end
```

`RSpec/MessageExpectation` enforces using either `expect` or `allow` for stubs:

```
# bad
expect(foo).to receive(:bar)

# good
allow(foo).to receive(:bar)
```

`RSpec/MultipleExpectations` enforces rules about having multiple `expect` calls in an `it` block

`RSpec/NestedGroups` enforces rules about how many `context` or `describe` blocks can be nested inside of others.

All of these cases are situational, and it should be left to the developer to determine the best way to write their tests.

**Comment by gaffneyc** [comment]
Thanks! Based on what you've put I agree on the changes. My only request would be to better document in `.rubocop.yml` what they're doing and why we're disabling them. The documentation that is there depends on knowing what they mean and the commit doesn't go into any detail so `git blame` isn't any help.

**Comment by gaffneyc** [comment]
And this PR will be hard to find once it's been merged.

**Comment by kopchickm** [comment]
100% agree. @albus522, can you amend the commit and provide more documentation, or add more documentation in the file?

**Comment by albus522** [comment]
@kopchickm it looks like you already did. You could just move it into the file

**Pull request merged**
